#!/bin/bash
set -x

[ -z "$VOLUME_NAME" ] && (echo "\$VOLUME_NAME must be defined"; exit 1)

etcd_dir="/volumes/$VOLUME_NAME"
etcd_path="$etcd_dir/btsync_secret"

SECRET=$(etcdctl get $etcd_path 2>/dev/null)
if [ -z "$SECRET" ] ; then
  etcdctl mkdir $etcd_dir 2>/dev/null
  etcdctl mk $etcd_path $(btsync --generate-secret) 2>/dev/null

  # Fetch the secret again just in case some other instance generated one at the
  # same file
  SECRET=$(etcdctl get $etcd_path)

  if [ -z "$SECRET" ] ; then
    echo "Failed to generate or set the btsync secret"
    exit 1;
  fi
fi


echo "Starting btsync with secret: $SECRET"

echo "{
    \"device_name\": \"Sync Server\",
    \"listening_port\": 55555,
    \"storage_path\": \"/btsync/.sync\",
    \"pid_file\": \"/var/run/btsync/btsync.pid\",
    \"check_for_updates\": false,
    \"use_upnp\": false,
    \"download_limit\": 0,
    \"upload_limit\": 0,
    \"shared_folders\": [
        {
            \"secret\": \"$SECRET\",
            \"dir\": \"/data\",
            \"use_relay_server\": true,
            \"use_tracker\": true,
            \"use_dht\": false,
            \"search_lan\": true,
            \"use_sync_trash\": false
        }
    ]
}" > /etc/btsync.conf

exec btsync --config /etc/btsync.conf --nodaemon
