#!/bin/bash
set -ex

[ -z "$SERVICE" ] && (echo "\$SERVICE must be defined"; exit 1)

SECRET=$(etcdctl get /service/$SERVICE/btsync_secret)
if [ -z "$SECRET" ] ; then
  etcdctl mk /service/$SERVICE $(btsync --generate-secret) || true
  SECRET=$(etcdctl get /service/$SERVICE/btsync_secret)
fi

echo "Starting btsync with secret: $SECRET"

echo "{
    \"device_name\": \"Sync Server\",
    \"listening_port\": 55555,
    \"storage_path\": \"/btsync/.sync\",
    \"pid_file\": \"/var/run/btsync/btsync.pid\",
    \"check_for_updates\": false,
    \"use_upnp\": false,
    \"download_limit\": 0,
    \"upload_limit\": 0,
    \"shared_folders\": [
        {
            \"secret\": \"$SECRET\",
            \"dir\": \"/data\",
            \"use_relay_server\": true,
            \"use_tracker\": true,
            \"use_dht\": false,
            \"search_lan\": true,
            \"use_sync_trash\": false
        }
    ]
}" > /etc/btsync.conf

exec btsync --config /etc/btsync.conf --nodaemon
